CREATE TABLE IF NOT EXISTS domains (
    id     UUID NOT NULL PRIMARY KEY UNIQUE DEFAULT (UUID_V7()),
    domain VARCHAR(255) NOT NULL UNIQUE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);
